### ISSUE TITLE
[Feature] Different descriptions for different protocol version

### ISSUE THREAD

**Issue by TheFloodDragon** [AlexProgrammerDE/PistonMOTD#244]
How nice it would be to see different motds in different versions.

Just like this:

```YAML
advanced:
    ProtocoledDescription:
       activated: true
       allowedProtocol: below 735
       text:
         - "Text1 Line1%newline%Text1 Line2"
         - "Text2 Line1%newline%Text2 Line2"
```

Hope for your reply, thanks!
